### ISSUE TITLE
Calls to ecodata are attempted using userId=

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocollect#1017]
There are stacktraces in the biocollect log files that seem to show calls to ecodata being attempted with ``userId=``, potentially indicating a programming error in biocollect code:

```
2018-04-10 10:02:47,334 ERROR [WebService] {error=Failed calling web service. Server returned HTTP response code: 400 for URL: https://ecodata.ala.org.au/ws/
comment/canUserEditOrDeleteComment?userId=&entityId=5c007041-2d60-4ad4-b5bb-f9a378996c2f&entityType=au.org.ala.ecodata.Activity URL= https://ecodata.ala.org.
au/ws/comment/canUserEditOrDeleteComment?userId=&entityId=5c007041-2d60-4ad4-b5bb-f9a378996c2f&entityType=au.org.ala.ecodata.Activity., statusCode=400, detai
l=<html><head><title>Apache Tomcat/7.0.52 (Ubuntu) - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525
D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;co
lor:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Aria
l,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.n
ame {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 400 - Missing userId, entityId or entityType</h1><HR size="1" noshade="nosh
ade"><p><b>type</b> Status report</p><p><b>message</b> <u>Missing userId, entityId or entityType</u></p><p><b>description</b> <u>The request sent by the clie
nt was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.52 (Ubuntu)</h3></body></html>}
java.io.IOException: Server returned HTTP response code: 400 for URL: https://ecodata.ala.org.au/ws/comment/canUserEditOrDeleteComment?userId=&entityId=5c007
041-2d60-4ad4-b5bb-f9a378996c2f&entityType=au.org.ala.ecodata.Activity
        at au.org.ala.biocollect.merit.WebService.doGet(WebService.groovy:315)
        at au.org.ala.biocollect.CommentService.listComments(CommentService.groovy:34)
        at au.org.ala.biocollect.CommentController.list(CommentController.groovy:52)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:110)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ansell** [comment]
Another similar but distinct stacktrace of this pattern is:

```
2018-04-10 06:55:21,547 ERROR [WebService] {error=Failed to get json from web service. class java.io.IOException Server returned HTTP response code: 400 for 
URL: https://ecodata.ala.org.au/ws/permissions/isUserAdminForProject?projectId=5ae0c656-2878-4c82-98aa-8368d5ceb02a&userId= URL= https://ecodata.ala.org.au/w
s/permissions/isUserAdminForProject?projectId=5ae0c656-2878-4c82-98aa-8368d5ceb02a&userId=., statusCode=400, detail=Required params not provided: userId, pro
jectId}
java.io.IOException: Server returned HTTP response code: 400 for URL: https://ecodata.ala.org.au/ws/permissions/isUserAdminForProject?projectId=5ae0c656-2878
-4c82-98aa-8368d5ceb02a&userId=
        at java.net.URLConnection.getContent(URLConnection.java:748)
        at au.org.ala.biocollect.merit.WebService.responseText(WebService.groovy:210)
        at au.org.ala.biocollect.merit.WebService.getJson(WebService.groovy:172)
        at au.org.ala.biocollect.merit.ProjectService.isUserAdminForProject(ProjectService.groovy:365)
        at au.org.ala.biocollect.merit.AclFilterFilters$_closure1_closure2_closure3.doCall(AclFilterFilters.groovy:78)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:110)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://ecodata.ala.org.au/ws/permissions/isUserAdminForProject?projectId=5a
e0c656-2878-4c82-98aa-8368d5ceb02a&userId=
        at java.net.URLConnection.getContentType(URLConnection.java:522)
        at au.org.ala.biocollect.merit.WebService.responseText(WebService.groovy:205)
        ... 12 more
```
