### ISSUE TITLE
Calls to lists are attempted using "null" for parameter values

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocollect#1018]
The biocollect log files show calls to lists.ala.org.au are being attempted with ``null`` for parameter values, indicating a potential programming issue in biocollect code:

```
2018-04-10 10:00:56,670 ERROR [WebService] {error=Failed to get json from web service. class java.io.IOException Server returned HTTP response code: 500 for 
URL: https://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null&order=null URL= https://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset
=null&order=null., statusCode=500, detail=<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="app.version" content=""/>
    <meta name="app.build" content=""/>
    <meta name="description" content="Atlas of Living Australia"/>
    <meta name="author" content="Atlas of Living Australia">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://www.ala.org.au/commonui-bs3/css/bootstrap.min.css" rel="stylesheet" media="all" />
    <link href="https://www.ala.org.au/commonui-bs3/css/ala-styles.css" rel="stylesheet" media="all" />
    <link rel="stylesheet" media="all" href="/assets/core-b723a29fac7a87ba1773e821f0390498.css"/>
    <link rel="stylesheet" media="all" href="/assets/core-screen-print-33302e79a81ebc2dea940c077b2450f1.css"/>
    <link rel="stylesheet" media="all" href="/assets/application-d0276424c1b4cb670e1e2e3356c2a461.css"/>
    <link href="http://www.ala.org.au/wp-content/themes/ala2011/images/favicon.ico" rel="shortcut icon"  type="image/x-icon"/>

    <!--[if lt IE 9]>
    <script type="text/javascript" src="/assets/html5.js" ></script>
    <![endif]-->
    <script type="text/javascript" src="/assets/head-8c8036233f3a7101077bd2c1b799e348.js" ></script>
    <script type="text/javascript" src="/assets/jquery-extensions-7b19c40c8f992cd9158cdeb038c17e80.js" ></script>

    <title>Grails Runtime Exception</title>
    
    
    <meta name="layout" content="main"/>
    <meta name="breadcrumbParent" content="/public/speciesLists,Species lists"/>
    <meta name="breadcrumb" content="Error"/>

</head>
<body class="" id="" onload="">



<!-- Header -->
<!-- Navbar start -->
  <nav class="navbar navbar-default navbar-fixed-top not-logged-in">
    <div class="container container-navbar">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="https://www.ala.org.au/">
          <img alt="Brand" src="https://www.ala.org.au/commonui-bs3/img/ala-logo-2016-inline.png">
        </a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div class="row row-search">
          <div class="col-xs-12 col-sm-4 col-md-6">
            <form id="global-search" class="banner" action="https://bie.ala.org.au/search" method="get" name="search-form">
              <div class="icon-addon addon-lg">
                <input type="text" placeholder="Search the Atlas ..." class="form-control autocomplete" id="biesearch" name="q">
                <label for="biesearch" class="glyphicon glyphicon-search" rel="tooltip" title="search"></label>
              </div>
            </form>
          </div>
          <div class="col-md-2 hidden-xs">
            <ul class="nav navbar-nav navbar-right nav-login">
              <li><a href='https://auth.ala.org.au/cas/login?service=https://lists.ala.org.au/ws/speciesList?sort%3Dnull%26max%3Dnull%26offset%3Dnull%26order%3Dnull' class='null'>Log in</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right nav-logged-in">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                  My profile
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="https://auth.ala.org.au/userdetails/myprofile/">View profile</a></li>
                  <li><a href="https://auth.ala.org.au/userdetails/registration/editAccount">Account settings</a></li>
                  <li class="divider"></li>
                  <li><a href='https://auth.ala.org.au/cas/login?service=https://lists.ala.org.au/ws/speciesList?sort%3Dnull%26max%3Dnull%26offset%3Dnull%26order%3Dnull' class='null'>Log in</a></li>
                </ul>
              </li>
            </ul>

          </div>
        </div><!-- End row -->

        <ul class="nav navbar-nav">
          <!-- <li class="active"><a href="#">Home</a></li> -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              Start exploring
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="https://lists.ala.org.au/iconic-species">Australian iconic species</a></li>
              <li><a href="https://biocache.ala.org.au/explore/your-area">Explore your area</a></li>
              <li><a href="http://regions.ala.org.au/">Explore regions</a></li>
              <li><a href="https://biocache.ala.org.au/search">Search occurrence records</a></li>
              <li class="divider"></li>
              <li><a href="https://www.ala.org.au/sites-and-services/">Sites &amp; services</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              Search &amp; analyse
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="https://collections.ala.org.au/">Browse natural history collections</a></li>
              <li><a href="https://collections.ala.org.au/datasets">Search datasets</a></li>
              <li><a href="https://downloads.ala.org.au">Download datasets</a>
              <li><a href="http://spatial.ala.org.au/">Spatial portal</a></li>
              <li class="divider"></li>
              <li><a href="https://dashboard.ala.org.au/">ALA dashboard</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              Participate
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="https://biocollect.ala.org.au/acsa">Join a Citizen Science project</a></li>
              <li><a href="https://sightings.ala.org.au/">Record a sighting in the ALA</a></li>
              <li><a href="https://www.ala.org.au/submit-dataset-to-ala/">Submit a dataset to the ALA</a></li>
              <li><a href="https://digivol.ala.org.au/">Digitise a record in DigiVol</a></li>
              <li><a href="https://www.ala.org.au/who-we-are/downloadable-tools/ala-mobile-app/">Mobile apps</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              Learn about the ALA
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="https://www.ala.org.au/who-we-are/">Who we are</a></li>
              <li class="divider"></li>
              <li><a href="https://www.ala.org.au/how-to-use-ala/">How to use the ALA</a></li>
              <li><a href="https://www.ala.org.au/how-to-work-with-data/">How to work with data</a></li>
              <li><a href="https://www.ala.org.au/how-to-cite-ala/">How to cite the ALA</a></li>
              <li class="divider"></li>
              <li><a href="https://www.ala.org.au/education-resources/">Education resources</a></li>
              <li><a href="https://www.ala.org.au/ala-and-indigenous-ecological-knowledge-iek/">Indigenous Ecological Knowledge</a></li>
              <li class="divider"></li>
              <li><a href="https://www.ala.org.au/blogs-news/">ALA Blog</a></li>
              <li class="divider"></li>
              <li><a href="https://www.ala.org.au/about-the-atlas/contact-us/">Contact us</a></li>
              <li><a href="https://www.ala.org.au/about-the-atlas/feedback-form/">Feedback form</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right visible-xs">
          <li><a href="https://auth.ala.org.au/userdetails/myprofile/"><span class="nav-login">View profile</span></a></li>
          <li><a href="https://auth.ala.org.au/userdetails/registration/editAccount"><span class="nav-login">Account settings</span></a></li>
          <li><a href='https://auth.ala.org.au/cas/login?service=https://lists.ala.org.au/ws/speciesList?sort%3Dnull%26max%3Dnull%26offset%3Dnull%26order%3Dnull' class='null'>Log in</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>
  <!-- End Navbar -->

<!-- End header -->
<!-- Breadcrumb -->

    <section id="breadcrumb">
        <div class="container">
            <div class="row">
                <ul class="breadcrumb-list">
                    <li><a href="https://www.ala.org.au">Home</a></li>
                    
                        
                        <li><a href="/public/speciesLists">Species lists</a></li>
                    
                    <li class="active">Error</li>
                </ul>
            </div>
        </div>
    </section>

<!-- End Breadcrumb -->
<!-- Container -->
<div class="container" id="main">
    
        
    
    
<header id="page-header">
    <div class="inner">
        <hgroup>
            <h1>Error page</h1>
        </hgroup>
    </div>
</header>
<div class="inner">
    <div><pre></pre></div>
    <div>org.grails.web.errors.GrailsWrappedRuntimeException: No signature of method: static java.lang.Math.min() is applicable for argument types: (null, java.lang.Integer) values: [null, 1000]
Possible solutions: min(int, int), min(double, double), min(float, float), min(long, long), find(), max(int, int)</div>
    <h1>Error 500: Internal Server Error</h1>
<dl class="error-details">
<dt>URI</dt><dd>/ws/speciesList</dd>
<dt>Class</dt><dd>groovy.lang.MissingMethodException</dd><dt>Message</dt><dd>No signature of method: static java.lang.Math.min() is applicable for argument types: (null, java.lang.Integer) values: [null, 1000]
Possible solutions: min(int, int), min(double, double), min(float, float), min(long, long), find(), max(int, int)</dd></dl><h2>Trace</h2><pre class="stack">    Line | Method
-&gt;&gt;   36 | getFilterListResult in au.org.ala.specieslist.QueryService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    152 | doCall              in au.org.ala.specieslist.WebServiceController$_closure1
|    223 | invoke . . . . . .  in org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker
|    188 | invoke              in org.grails.core.DefaultGrailsControllerClass
|     90 | handle . . . . . .  in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|    967 | doDispatch          in org.springframework.web.servlet.DispatcherServlet
|    901 | doService . . . . . in     &#39;&#39;
|    970 | processRequest      in org.springframework.web.servlet.FrameworkServlet
|    861 | doGet . . . . . . . in     &#39;&#39;
|    846 | service             in     &#39;&#39;
|     55 | doFilterInternal .  in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|     77 | doFilterInternal    in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|     67 | doFilterInternal .  in org.grails.web.filters.HiddenHttpMethodFilter
|    181 | doFilter            in au.org.ala.cas.client.UriFilter
|     97 | doFilter . . . . .  in org.jasig.cas.client.session.SingleSignOutFilter
|    208 | doFilterInternal    in org.springframework.security.web.FilterChainProxy
|    177 | doFilter . . . . .  in     &#39;&#39;
|    117 | doFilter            in org.springframework.boot.web.support.ErrorPageFilter
|     61 | access$000 . . . .  in     &#39;&#39;
|     92 | doFilterInternal    in org.springframework.boot.web.support.ErrorPageFilter$1
|    110 | doFilter . . . . .  in org.springframework.boot.web.support.ErrorPageFilter
|   1149 | runWorker           in java.util.concurrent.ThreadPoolExecutor
|    624 | run . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    748 | run                 in java.lang.Thread
</pre>
</div>

</div><!-- End container #main  -->

<!-- Footer -->
 <footer>
    <!-- Container -->
    <div class="container footer-container ">
      <hr class="footer-border">
      <div class="row footer-nav">

        <div class="col-md-12 margin-bottom-2">
          <h2 class="heading-large margin-bottom-quarter-1">Atlas of Living Australia</h2>
          <h3 class="promotional">Sharing biodiversity knowledge to shape our future</h3>
        </div>

        <div class="col-xs-6 col-sm-3 col-lg-3 hidden-print">
          <h5>Start exploring</h5>
          <ul class="link-list">
            <li><a href="https://lists.ala.org.au/iconic-species">Australian iconic species</a></li>
            <li><a href="https://biocache.ala.org.au/explore/your-area">Explore your area</a></li>
            <li><a href="http://regions.ala.org.au/">Explore regions</a></li>
            <li><a href="https://biocache.ala.org.au/search">Search occurrence records</a></li>
            <li><a href="https://www.ala.org.au/sites-and-services/">Sites &amp; services</a></li>
          </ul>
        </div>

        <div class="col-xs-6 col-sm-3 col-lg-3 hidden-print">
          <h5>Search &amp; analyse</h5>
          <ul class="link-list">
            <li><a href="https://collections.ala.org.au/">Browse natural history collections</a></li>
            <li><a href="https://collections.ala.org.au/datasets">Search datasets</a></li>
            <li><a href="https://downloads.ala.org.au">Download datasets</a>
            <li><a href="http://spatial.ala.org.au/">Spatial portal</a></li>
            <li><a href="https://dashboard.ala.org.au/">ALA dashboard</a></li>
          </ul>
        </div>

        <div class="clearfix visible-xs-block">
          <!-- This fixes the alignment issues of the footer columns -->
        </div>

        <div class="col-xs-6 col-sm-3 col-lg-3 hidden-print">
          <h5 class="footer-second-row">Participate</h5>
          <ul class="link-list">
            <li><a href="https://biocollect.ala.org.au/acsa">Join a citizen science project</a></li>
            <li><a href="https://sightings.ala.org.au/">Record a sighting</a></li>
            <li><a href="https://www.ala.org.au/submit-dataset-to-ala/">Submit a dataset to the ALA</a></li>
            <li><a href="https://digivol.ala.org.au/">Digitise a record</a></li>
            <li><a href="https://www.ala.org.au/who-we-are/downloadable-tools/ala-mobile-app/">Mobile apps</a></li>
          </ul>
        </div>

        <div class="col-xs-6 col-sm-3 col-lg-3 hidden-print">
          <h5 class="footer-second-row">Learn about the ALA</h5>
          <ul class="link-list">
            <li><a href="https://www.ala.org.au/who-we-are/">Who we are</a></li>
            <li><a href="https://www.ala.org.au/how-to-use-ala/">How to use the ALA</a></li>
            <li><a href="https://www.ala.org.au/how-to-work-with-data/">How to work with data</a></li>
            <li><a href="https://www.ala.org.au/how-to-cite-ala/">How to cite the ALA</a></li>
            <li><a href="https://www.ala.org.au/education-resources/">Education resources</a></li>
            <li><a href="https://www.ala.org.au/ala-and-indigenous-ecological-knowledge-iek/">Indigenous Ecological Knowledge</a></li>
            <li><a href="https://www.ala.org.au/blogs-news/">ALA Blog</a></li>
            <li><a href="https://www.ala.org.au/about-the-atlas/contact-us/">Contact us</a></li>
            <li><a href="https://www.ala.org.au/about-the-atlas/feedback-form/">Feedback form</a></li>
          </ul>
        </div>
      </div>

      <div class="row footer-bonus">
        <div class="col-md-4 col-sm-12 footer-bonus-item">
          <h5 class="footer-bonus-heading">Explore the Spatial Portal</h5>
          <a href="http://spatial.ala.org.au/" title="Spatial portal" class="footer-bonus-link">
            <img class="img-responsive" src="https://www.ala.org.au/commonui-bs3/img/footer-bonus-spatial-portal-icon.png" alt="Spatial Portal icon">
          </a>
          <p class="footer-bonus-description"><a href="http://spatial.ala.org.au/">Explore species occurrence records</a> in the context of their environment. Find records and model species distributions. Export reports, maps and data.</p>
        </div>
        <div class="col-md-4 col-sm-12 footer-bonus-item">
          <h5 class="footer-bonus-heading">Join a Citizen Science Project</h5>
          <a href="https://biocollect.ala.org.au/acsa" title="Contribute your sightings" class="footer-bonus-link">
            <img class="img-responsive" src="https://www.ala.org.au/commonui-bs3/img/footer-bonus-cit-science-icon.png" alt="Citizen Science icon">
          </a>
          <p class="footer-bonus-description">Find out how you can <a href="https://biocollect.ala.org.au/acsa">contribute to a citizen science project</a> in your area, or explore one of the many citizen science projects supported by the ALA.</p>
        </div>
        <div class="col-md-4 col-sm-12 footer-bonus-item">
          <h5 class="footer-bonus-heading">Record a sighting</h5>
          <a href="https://sightings.ala.org.au/" title="Did you see something?" class="footer-bonus-link">
            <img class="img-responsive" src="https://www.ala.org.au/commonui-bs3/img/footer-bonus-record-sighting-icon.png" alt="Sightings icon">
          </a>
          <p class="footer-bonus-description">Did you see something? Photograph something? <a href="https://sightings.ala.org.au/">Contribute your sighting</a> to the Atlas of Living Australia.</p>
        </div>

      </div>
      <!-- Acknowledgement section -->
      <div class="row col-sm-12 acknowledgement-callout acknowledgement-callout-ala">
        <div class="col-md-10 col-sm-12">
          <h4 class="margin-bottom-half-1">Acknowledgement of Traditional Owners and Country</h4>
          <p>The Atlas of Living Australia acknowledges Australia's Traditional Owners and pays respect to the past and present Elders of the nation's Aboriginal and Torres Strait Islander communities. We honour and celebrate the spiritual, cultural and customary connections of Traditional Owners to country and the biodiversity that forms part of that country.</p>
        </div>
        <div class="clearfix"></div>
      </div>
      <!-- Logo section -->
      <div class="row">
        <div class="col-md-12">
          <h5 class="footer-bonus-heading">The ALA is made possible by contributions from its partners, is supported by NCRIS and hosted by CSIRO</h5>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 footer-bonus-brands">
          <a href="https://www.education.gov.au/national-collaborative-research-infrastructure-strategy-ncris" class="img-responsive" id="ncris">NCRIS</a>
          <a href="https://www.csiro.au/" id="csiro">CSIRO</a>
          <a href="https://www.gbif.org/" class="img-responsive" id="gbif">GBIF</a>
        </div>
      </div>
      <!-- End logo section -->

      <div class="row">
        <div class="col-md-12">
          <ul class="footer-list">
            <li class="footer-item footer-social">
              <a id="twitter" title="Twitter" href="https://twitter.com/#!/atlaslivingaust"><img src="https://www.ala.org.au/commonui-bs3/img/social_twitter_29px.png" alt="Twitter" /></a>
            </li>
            <li class="footer-item footer-social">
              <a id="facebook" title="Facebook" href="https://www.facebook.com/atlasoflivingaustralia"><img src="https://www.ala.org.au/commonui-bs3/img/social_facebook_29px.png" alt="Facebook" /></a>
            </li>
            <li class="footer-item footer-item-text footer-item-start"><a href="https://www.ala.org.au/who-we-are/terms-of-use/#Copyright">Copyright</a></li>
            <li class="footer-item footer-item-text"><a href="https://www.ala.org.au/about-the-atlas/terms-of-use/">Terms of use</a></li>
            <li class="footer-item footer-item-text"><a href="https://www.ala.org.au/about-the-atlas/contact-us/">Contact us</a></li>
            <li class="footer-item footer-item-status"><a href="http://status.ala.org.au/">System status</a></li>
          </ul>
        </div>
      </div>
    </div><!-- End Container -->
  </footer>

  <!-- Creative commons bar -->
  <div class="alert alert-creativecommons hidden-print" role="alert">
    <div class="container alert-container">
      <div class="row-fluid">
        <div class="col-md-12">
          <p class="alert-text text-creativecommons">
            This work is licensed under a <a href="https://creativecommons.org/licenses/by/3.0/au/">Creative Commons Attribution 3.0 Australia License</a>&ensp;<a rel="license" href="https://creativecommons.org/licenses/by/3.0/au/"><img alt="Creative Commons License" style="border-width:0" src="https://licensebuttons.net/l/by/3.0/80x15.png"></a>
          </p>
        </div>
      </div>
    </div>
  </div><!-- End Creative commons bar -->
<!-- End footer -->

    <script type="text/javascript" src="https://www.ala.org.au/commonui-bs3/js/application.js"></script>


    <script type="text/javascript" src="https://www.ala.org.au/commonui-bs3/js/bootstrap.min.js"></script>



</body>
</html>
}
java.io.IOException: Server returned HTTP response code: 500 for URL: https://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null&order=null
        at java.net.URLConnection.getContent(URLConnection.java:748)
        at au.org.ala.biocollect.merit.WebService.responseText(WebService.groovy:210)
        at au.org.ala.biocollect.merit.WebService.getJson(WebService.groovy:172)
        at au.org.ala.biocollect.merit.SpeciesService.searchSpeciesList(SpeciesService.groovy:149)
        at au.org.ala.biocollect.merit.SearchController.searchSpeciesList(SearchController.groovy:30)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
        at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:110)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: https://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null&order=null
        at java.net.URLConnection.getContentType(URLConnection.java:522)
        at au.org.ala.biocollect.merit.WebService.responseText(WebService.groovy:205)
        ... 12 more
```

**Comment by ansell** [comment]
This is still a current issue:

```
$ grep -rni 'sort=null' /var/log/tomcat7/
/var/log/tomcat7/biocollect.log.2016-05-09T06:17:22Z:847:2016-05-04 20:01:04,581 ERROR [WebService] {error=Failed to get json from web service. class java.io.IOException Server returned HTTP response code: 500 for URL: http://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null URL= http://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null., statusCode=500, detail=<!DOCTYPE html>
/var/log/tomcat7/biocollect.log.2016-05-09T06:17:22Z:1157:java.io.IOException: Server returned HTTP response code: 500 for URL: http://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null
/var/log/tomcat7/biocollect.log.2016-05-09T06:17:22Z:1172:Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null
/var/log/tomcat7/biocollect.log.2016-05-06T07:59:59Z:847:2016-05-04 20:01:04,581 ERROR [WebService] {error=Failed to get json from web service. class java.io.IOException Server returned HTTP response code: 500 for URL: http://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null URL= http://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null., statusCode=500, detail=<!DOCTYPE html>
/var/log/tomcat7/biocollect.log.2016-05-06T07:59:59Z:1157:java.io.IOException: Server returned HTTP response code: 500 for URL: http://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null
/var/log/tomcat7/biocollect.log.2016-05-06T07:59:59Z:1172:Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null
/var/log/tomcat7/biocollect.log:6000:2019-08-22 12:36:42,272 ERROR [WebService] {error=Failed to get json from web service. class java.io.IOException Server returned HTTP response code: 500 for URL: https://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null&order=null URL= https://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null&order=null., statusCode=500, detail=<!DOCTYPE html>
/var/log/tomcat7/biocollect.log:6882:java.io.IOException: Server returned HTTP response code: 500 for URL: https://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null&order=null
/var/log/tomcat7/biocollect.log:6899:Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: https://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null&order=null
/var/log/tomcat7/biocollect.log.2016-05-13T12:34:23Z:847:2016-05-04 20:01:04,581 ERROR [WebService] {error=Failed to get json from web service. class java.io.IOException Server returned HTTP response code: 500 for URL: http://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null URL= http://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null., statusCode=500, detail=<!DOCTYPE html>
/var/log/tomcat7/biocollect.log.2016-05-13T12:34:23Z:1157:java.io.IOException: Server returned HTTP response code: 500 for URL: http://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null
/var/log/tomcat7/biocollect.log.2016-05-13T12:34:23Z:1172:Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://lists.ala.org.au/ws/speciesList?sort=null&max=null&offset=null
```

**Comment by ansell** [comment]
The root partition filled up so the logging will be incomplete, but there is one entry there from the last 24 hours
