### ISSUE TITLE
Cannot update/save an activity of a survey which contains species but they are not recognized as species

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/biocollect#1029]
Error:
Error creating output for activity 6fb4beee-9142-41ed-9d9a-7eafa42d8f45 - Cannot invoke method toLowerCase() on null object, name=Aquatic Macro-invertebrates 

link:
https://biocollect-test.ala.org.au/actwaterwatch/bioActivity/edit/6fb4beee-9142-41ed-9d9a-7eafa42d8f45?returnTo=%2Factwaterwatch%2Fproject%2Findex%2F754eab77-d26d-4357-952c-bf265dca0e37

Possible related reason:
the survey ( https://biocollect-test.ala.org.au/actwaterwatch/project/index/754eab77-d26d-4357-952c-bf265dca0e37) has species, but not recognised by our system. 

In admin->survey->species
Warning:  You have not selected any form in step 4 or the form does not contain any species field.

------------------------------------------------------------------------------------

Ecodata throw exceptions:

ERROR [ActivityController]  {error=Error creating output for activity 6fb4beee-9142-41ed-9d9a-7eafa42d8f45 - Cannot invoke method toLowerCase() on null object, name=Aquatic Macro-invertebrates (SIGNAL2 method)}

Error creating output for activity 6fb4beee-9142-41ed-9d9a-7eafa42d8f45 - Cannot invoke method toLowerCase() on null object
java.lang.NullPointerException: Cannot invoke method toLowerCase() on null object
	at au.org.ala.ecodata.converter.RecordConverter$_convertRecords_closure1.doCall(RecordConverter.groovy:74)
	at au.org.ala.ecodata.converter.RecordConverter.convertRecords(RecordConverter.groovy:73)
	at au.org.ala.ecodata.OutputService.createOrUpdateRecordsForOutput(OutputService.groovy:192)
	at au.org.ala.ecodata.OutputService.create(OutputService.groovy:156)
	at au.org.ala.ecodata.ActivityService$_doUpdate_closure28.doCall(ActivityService.groovy:441)
	at au.org.ala.ecodata.ActivityService.doUpdate(ActivityService.groovy:428)
	at au.org.ala.ecodata.ActivityService.update(ActivityService.groovy:392)
	at au.org.ala.ecodata.ActivityController.update(ActivityController.groovy:89)

**Comment by temi** [comment]
The issue is that this activity has been deleted.
