### ISSUE TITLE
Logback throws error when string is not passed 

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/biocollect#1213]
The actual exception is not logged due to this: 

![image](https://user-images.githubusercontent.com/1606595/67728901-198dff80-fa43-11e9-930a-0702c1c82a7a.png)

```
2019-10-29 11:52:55.537 ERROR --- [nio-8087-exec-6] StackTrace                               : Full Stack Trace:

org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '{error=No signature of method: ch.qos.logback.classic.Logger.error() is applicable for argument types: (java.util.LinkedHashMap, java.net.ConnectException) values: [[error:ecodata service not available. URL= http://devt.ala.org.au:8081/ecodata/ws/hub/.], ...]
Possible solutions: error(java.lang.String), error(java.lang.String, [Ljava.lang.Object;), error(java.lang.String, java.lang.Object), error(java.lang.String, java.lang.Throwable), error(org.slf4j.Marker, java.lang.String), error(java.lang.String, java.lang.Object, java.lang.Object)}' with class 'java.util.LinkedHashMap' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List(java.util.LinkedHashMap)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:416)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:332)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnCollection(DefaultTypeTransformation.java:280)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:232)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:616)
	at au.org.ala.biocollect.merit.SettingService.listHubs(SettingService.groovy:179)
	at au.org.ala.biocollect.merit.SettingService$listHubs$3.callCurrent(Unknown Source)
	at au.org.ala.biocollect.merit.SettingService.isValidHub(SettingService.groovy:40)
	at au.org.ala.biocollect.merit.SettingService$isValidHub$2.call(Unknown Source)
	at au.org.ala.biocollect.UrlMappings.isHubValid(UrlMappings.groovy:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:169)
	at au.org.ala.biocollect.UrlMappings$__clinit__closure1$_closure4$_closure20$_closure21.doCall(UrlMappings.groovy:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:420)
	at au.org.ala.biocollect.UrlMappings$__clinit__closure1$_closure4$_closure20$_closure21.call(UrlMappings.groovy)
	

```

**Comment by patkyn** [comment]
Going through all biocollect and ecodata code to address this.

**Comment by patkyn** [comment]
The above code will have to be modified to pass in string like this
![image](https://user-images.githubusercontent.com/1606595/67729088-de400080-fa43-11e9-9f57-f49258840079.png)

This produce the proper exception logging

![image](https://user-images.githubusercontent.com/1606595/67729112-edbf4980-fa43-11e9-86a2-634133e9daec.png)
