### ISSUE TITLE
Download data fails for CoralWatch

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1360]
Cause:
ProjectActivity in CoralWatch project has a large number of associated sites. It is exported into a cell in excel sheet. String representing list of sites is larger than the maximum limit for a cell (32767 characters). It throws the below exception.

```
java.lang.IllegalArgumentException: The maximum length of cell contents (text) is 32767 characters
	at org.apache.poi.ss.usermodel.CellBase.checkLength(CellBase.java:309)
	at org.apache.poi.ss.usermodel.CellBase.setCellValue(CellBase.java:323)
	at org.apache.poi.ss.usermodel.Cell$setCellValue.call(Unknown Source)
	at pl.touk.excel.export.abilities.CellManipulationAbility.putCellValue(CellManipulationAbility.groovy:18)
	at pl.touk.excel.export.abilities.CellManipulationAbility$putCellValue.call(Unknown Source)
	at pl.touk.excel.export.abilities.RowManipulationAbility$_fillRowWithValues_closure1.doCall(RowManipulationAbility.groovy:29)
	at sun.reflect.GeneratedMethodAccessor289.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:405)
...
```

**Comment by temi** [comment]
https://upsource.ala.org.au/ecodata/review/ECDT-CR-96

**Comment by yasima-csiro** [comment]
Tested small and large data download for Coralwatch. Small data sets downloaded the data straightway.Large data sets were downloaded asynchronously. All the site details were downloaded without an issue.
