### ISSUE TITLE
Downloading image from primary server throws an exception due to invalid URL

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#1518]
This happens on biocollect/ecodata test server. Mostly since it does not have production setup i.e. reporting server. And downloads are happening on the primary server.
```
2023-03-23 13:04:24.565 ERROR --- [pool-1-thread-2] au.org.ala.ecodata.WebService            : [error:Failed calling web service. class java.net.MalformedURLException no protocol: /document/download/dr364%7C%7C82ef50b7-1d63-410a-ba14-0a8eddbd64bb%7C%7C0_100_5167.jpg URL= /document/download/dr364%7C%7C82ef50b7-1d63-410a-ba14-0a8eddbd64bb%7C%7C0_100_5167.jpg., statusCode:, detail:null]

java.net.MalformedURLException: no protocol: /document/download/dr364%7C%7C82ef50b7-1d63-410a-ba14-0a8eddbd64bb%7C%7C0_100_5167.jpg
        at java.base/java.net.URL.<init>(URL.java:645)
        at java.base/java.net.URL.<init>(URL.java:541)
        at java.base/java.net.URL.<init>(URL.java:488)
        at java.base/jdk.internal.reflect.GeneratedConstructorAccessor413.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
        at au.org.ala.ecodata.WebService.configureConnection(WebService.groovy:77)
        at au.org.ala.ecodata.WebService.configureConnection(WebService.groovy)
        at au.org.ala.ecodata.WebService.getStream(WebService.groovy:57)
...

```

**Comment by temi** [comment]
This is due to host name not being present for async download. Chris's fix should solve it.
