### ISSUE TITLE
Errors creating data providers in Collectory

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocollect#424]
The production ecodata logs have a lot of errors relating to Collectory integration:
ERROR StackTrace  - Full Stack Trace:
java.io.IOException: Server returned HTTP response code: 400 for URL: http://collections.ala.org.au/ws/dataProvider/
        at au.org.ala.ecodata.WebService.doPost(WebService.groovy:181)
        at au.org.ala.ecodata.CollectoryService.createDataProviderAndResource(CollectoryService.groovy:94)
        at au.org.ala.ecodata.ProjectService$_establishCollectoryLinkForProject_closure11.doCall(ProjectService.groovy:218)
        at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
        at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-01-27 12:48:53,375 [Actor Thread 1] ERROR StackTrace  - Full Stack Trace:
java.lang.Exception: Failed to create Collectory data provider: Failed calling web service. Server returned HTTP response code: 400 for URL: http://collections.ala.org.au/ws/dataProvider/ URL= http://collections.ala.org.au/ws/dataProvider/. grails.validation.ValidationErrors: 1 errors
Field error in object 'au.org.ala.collectory.DataProvider' on field 'name': rejected value [null]; codes [au.org.ala.collectory.DataProvider.name.nullable.error.au.org.ala.collectory.DataProvider.name,au.org.ala.collectory.DataProvider.name.nullable.error.name,au.org.ala.collectory.DataProvider.name.nullable.error.java.lang.String,au.org.ala.collectory.DataProvider.name.nullable.error,dataProvider.name.nullable.error.au.org.ala.collectory.DataProvider.name,dataProvider.name.nullable.error.name,dataProvider.name.nullable.error.java.lang.String,dataProvider.name.nullable.error,au.org.ala.collectory.DataProvider.name.nullable.au.org.ala.collectory.DataProvider.name,au.org.ala.collectory.DataProvider.name.nullable.name,au.org.ala.collectory.DataProvider.name.nullable.java.lang.String,au.org.ala.collectory.DataProvider.name.nullable,dataProvider.name.nullable.au.org.ala.collectory.DataProvider.name,dataProvider.name.nullable.name,dataProvider.name.nullable.java.lang.String,dataProvider.name.nullable,nullable.au.org.ala.collectory.DataProvider.name,nullable.name,nullable.java.lang.String,nullable]; arguments [Name,class au.org.ala.collectory.DataProvider]; default message [Property [{0}] of class [{1}] cannot be null]

 Associated followup emails are not being sent due to:
ERROR StackTrace  - Full Stack Trace:
org.springframework.mail.MailParseException: Could not parse mail; nested exception is javax.mail.internet.AddressException: Illegal address in string ``[:]''
        at grails.plugin.mail.MailMessageBuilder.to(MailMessageBuilder.groovy:182)
        at grails.plugin.mail.MailMessageBuilder.to(MailMessageBuilder.groovy:189)
        at au.org.ala.ecodata.EmailService$_sendEmail_closure3.doCall(EmailService.groovy:34)
        at grails.plugin.mail.MailService.sendMail(MailService.groovy:53)
        at grails.plugin.mail.MailService.sendMail(MailService.groovy:59)
        at au.org.ala.ecodata.EmailService.sendEmail(EmailService.groovy:32)
        at au.org.ala.ecodata.EmailService.sendEmail(EmailService.groovy:10)
        at au.org.ala.ecodata.ProjectService$_establishCollectoryLinkForProject_closure13.doCall(ProjectService.groovy:228)
        at org.grails.async.factory.gpars.GparsPromise$_onError_closure2.doCall(GparsPromise.groovy:72)

**Comment by chrisala** [comment]
The problem was that if a partial update of a project is performed (as can happen in MERIT at least), some mandatory fields were missing from the data provider creation call. 
The email error is due to missing configuration in ecodata in prod. (this has been added).

**Comment by chrisala** [comment]
https://upsource.ala.org.au/ecodata/review/ECODATA-CR-29
