### ISSUE TITLE
New Project > Organisation list is missing due to read timeout.

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#686]
2016-09-02 16:01:28,511 ERROR [WebService] {error=Timed out getting json. URL= https://ecodata-test.ala.org.au/ws/organisation.}
3572 java.net.SocketTimeoutException: Read timed out
3573         at java.net.URLConnection.getContent(URLConnection.java:739)

**Comment by nickdos** [comment]
Is this an issue with ecodata or is it flowing through to an issue in collectory?

**Comment by sat01a** [comment]
Issue is related to the way BioCollect implementation:
It's fetching all organisation details instead of paginating it.

**Comment by javier-molina** [comment]
Organisation pagination as implemented in MERIT:

https://fieldcapture-test.ala.org.au/organisation/list 
https://github.com/AtlasOfLivingAustralia/fieldcapture/blob/master/grails-app/views/organisation/list.gsp
https://github.com/AtlasOfLivingAustralia/fieldcapture-hubs/blob/master/fieldcapture-hubs-plugin/web-app/js/organisation.js#L230

**Comment by javier-molina** [comment]
An example of the issue, even caused when displaying a single project

`==> biocollect.log <==
2016-12-08 12:28:55,310 ERROR [WebService] {error=Timed out getting json. URL= https://ecodata-test.ala.org.au/ws/organisation.}
java.net.SocketTimeoutException: Read timed out
	at java.net.URLConnection.getContent(URLConnection.java:748)
	at au.org.ala.biocollect.merit.WebService.responseText(WebService.groovy:202)
	at au.org.ala.biocollect.merit.WebService.getJson(WebService.groovy:164)
	at au.org.ala.biocollect.merit.MetadataService$_organisationList_closure19.doCall(MetadataService.groovy:211)
	at au.org.ala.biocollect.merit.CacheService.get(CacheService.groovy:31)
	at au.org.ala.biocollect.merit.MetadataService.organisationList(MetadataService.groovy:210)
	at au.org.ala.biocollect.merit.ProjectController.index(ProjectController.groovy:179)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:110)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at java.net.URLConnection.getContentType(URLConnection.java:522)
	at au.org.ala.biocollect.merit.WebService.responseText(WebService.groovy:197)
	... 14 more
`

**Comment by javier-molina** [comment]
https://github.com/AtlasOfLivingAustralia/biocollect/pull/710

**Comment by sat01a** [comment]
Feedback:
1. Can we remove empty organisation name from the list?
