### ISSUE TITLE
Missing models from JS for photopoint surveys

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocollect#818]
https://biocollect-test.ala.org.au/bioActivity/create/72bf3cd6-a511-46d9-b3f7-71994d898e0d
Photo Points > Attach Photo 

the above fails with

```
ElDZ4bhTU76oc6HW6s96GDGrCRwogXGdGHlRvNhNzG5.js:5789 Uncaught ReferenceError: ImageViewModel is not defined
    at https://biocollect-test.ala.org.au/static/ElDZ4bhTU76oc6HW6s96GDGrCRwogXGdGHlRvNhNzG5.js:5789:41
    at Array.forEach (native)
    at HTMLTableSectionElement.<anonymous> (https://biocollect-test.ala.org.au/static/ElDZ4bhTU76oc6HW6s96GDGrCRwogXGdGHlRvNhNzG5.js:5772:30)
    at HTMLTableSectionElement.dispatch (https://biocollect-test.ala.org.au/static/t5OGphSUjwdNOoxNKgdRTTh1RBtmzhMXxHDYYeR4lYj.js:3:8436)
    at HTMLTableSectionElement.r.handle (https://biocollect-test.ala.org.au/static/t5OGphSUjwdNOoxNKgdRTTh1RBtmzhMXxHDYYeR4lYj.js:3:5139)
    at Object.trigger (https://biocollect-test.ala.org.au/static/t5OGphSUjwdNOoxNKgdRTTh1RBtmzhMXxHDYYeR4lYj.js:3:7537)
    at Object.e.event.trigger (https://biocollect-test.ala.org.au/static/hnbQRQpYmXB6aSpR2hFr3vtCEgr0bYmKO6QhRRVFZ5B.js:2:6732)
    at HTMLTableSectionElement.<anonymous> (https://biocollect-test.ala.org.au/static/t5OGphSUjwdNOoxNKgdRTTh1RBtmzhMXxHDYYeR4lYj.js:3:15404)
    at Function.each (https://biocollect-test.ala.org.au/static/t5OGphSUjwdNOoxNKgdRTTh1RBtmzhMXxHDYYeR4lYj.js:2:2973)
    at e.fn.init.each (https://biocollect-test.ala.org.au/static/t5OGphSUjwdNOoxNKgdRTTh1RBtmzhMXxHDYYeR4lYj.js:2:835)
```

https://biocollect-test.ala.org.au/bioActivity/index/a7fbed63-7eff-45d3-bf25-acfe2471b355?returnTo=%2Fbiocollect%2Fproject%2Findex%2Fbbbacde4-a385-4d27-8401-fc94f382699c

The above fails with:

```
Uncaught ReferenceError: DocumentViewModel is not defined
    at photoPointPhoto (a7fbed63-7eff-45d3-bf25-acfe2471b355?returnTo=%2Fbiocollect%2Fproject%2Findex%2Fbbbacde4-a385-4d27-…:1110)
    at Object.<anonymous> (a7fbed63-7eff-45d3-bf25-acfe2471b355?returnTo=%2Fbiocollect%2Fproject%2Findex%2Fbbbacde4-a385-4d27-…:1032)
    at Function.each (t5OGphSUjwdNOoxNKgdRTTh1RBtmzhMXxHDYYeR4lYj.js:2)
    at photoPointPhotos (a7fbed63-7eff-45d3-bf25-acfe2471b355?returnTo=%2Fbiocollect%2Fproject%2Findex%2Fbbbacde4-a385-4d27-…:1031)
    at Object.<anonymous> (a7fbed63-7eff-45d3-bf25-acfe2471b355?returnTo=%2Fbiocollect%2Fproject%2Findex%2Fbbbacde4-a385-4d27-…:942)
    at Function.each (t5OGphSUjwdNOoxNKgdRTTh1RBtmzhMXxHDYYeR4lYj.js:2)
    at new PhotoPointViewModel (a7fbed63-7eff-45d3-bf25-acfe2471b355?returnTo=%2Fbiocollect%2Fproject%2Findex%2Fbbbacde4-a385-4d27-…:938)
    at new ViewModel (a7fbed63-7eff-45d3-bf25-acfe2471b355?returnTo=%2Fbiocollect%2Fproject%2Findex%2Fbbbacde4-a385-4d27-…:1499)
    at HTMLDocument.<anonymous> (a7fbed63-7eff-45d3-bf25-acfe2471b355?returnTo=%2Fbiocollect%2Fproject%2Findex%2Fbbbacde4-a385-4d27-…:1503)
    at j (t5OGphSUjwdNOoxNKgdRTTh1RBtmzhMXxHDYYeR4lYj.js:2)

```

This needs to be fixed

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-224
