### ISSUE TITLE
JS Error while creating a survey in Prod

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocollect#851]
The survey below will throw a JS error.

https://biocollect.ala.org.au/acsa/bioActivity/create/25e2a6d1-a9d2-405d-90a5-a3ad63975254

**Comment by javier-molina** [comment]
This below is the output in the console
`Zooming to project area
l8OSgxgphMyzqKRHkTbQxG8GgPFB1cDt95SPdzGTqhS.js:6 Uncaught TypeError: Cannot read property 'lat' of undefined
    at o.LatLngBounds.getNorth (https://biocollect.ala.org.au/static/l8OSgxgphMyzqKRHkTbQxG8GgPFB1cDt95SPdzGTqhS.js:6:16158)
    at o.LatLngBounds.getNorthWest (https://biocollect.ala.org.au/static/l8OSgxgphMyzqKRHkTbQxG8GgPFB1cDt95SPdzGTqhS.js:6:15869)
    at e.getBoundsZoom (https://biocollect.ala.org.au/static/l8OSgxgphMyzqKRHkTbQxG8GgPFB1cDt95SPdzGTqhS.js:6:23407)
    at e.fitBounds (https://biocollect.ala.org.au/static/l8OSgxgphMyzqKRHkTbQxG8GgPFB1cDt95SPdzGTqhS.js:6:19954)
    at zoomToProjectArea (https://biocollect.ala.org.au/static/Dw2fkkT39Dvccbpt1Ok38xmMETOWUolIpYzblGTqAEE.js:267:25)
    at enmapify (https://biocollect.ala.org.au/static/Dw2fkkT39Dvccbpt1Ok38xmMETOWUolIpYzblGTqAEE.js:490:9)
    at new (anonymous function) (https://biocollect.ala.org.au/acsa/bioActivity/create/25e2a6d1-a9d2-405d-90a5-a3ad63975254;jsessionid=86A68DB4CF5CDBA835FFA1C6C6F237B5:1388:13)
    at HTMLDocument.<anonymous> (https://biocollect.ala.org.au/acsa/bioActivity/create/25e2a6d1-a9d2-405d-90a5-a3ad63975254;jsessionid=86A68DB4CF5CDBA835FFA1C6C6F237B5:1576:37)
    at j (https://biocollect.ala.org.au/static/t5OGphSUjwdNOoxNKgdRTTh1RBtmzhMXxHDYYeR4lYj.js:2:27244)
    at Object.fireWith [as resolveWith] (https://biocollect.ala.org.au/static/t5OGphSUjwdNOoxNKgdRTTh1RBtmzhMXxHDYYeR4lYj.js:2:28057)`

Initial analysis suggest that the Biocollect code does not deal correctly with sites defined by pid as opposed to those where the polygon, square, etc is defined manually.

A possible  workaround to try in the meantime for prod is to disable the Zoom to project area survey json configuration setting

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/biocollect/review/BIOCOLLECT-CR-232
