### ISSUE TITLE
Error saving site when pid is selected. Validation failing

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocollect#977]
`*** /var/log/tomcat7//ecodata-stacktrace.log ***
2017-11-24 11:42:27,823 [http-bio-8080-exec-3] ERROR StackTrace  - Full Stack Trace:
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at org.geotools.geojson.GeoJSONUtil.createCoordinate(GeoJSONUtil.java:212)
	at org.geotools.geojson.geom.GeometryHandlerBase.coordinate(GeometryHandlerBase.java:54)
	at org.geotools.geojson.geom.PolygonHandler.endArray(PolygonHandler.java:88)
	at org.geotools.geojson.RecordingHandler$6.run(RecordingHandler.java:90)
	at org.geotools.geojson.RecordingHandler.replay(RecordingHandler.java:127)
	at org.geotools.geojson.geom.GeometryHandler.primitive(GeometryHandler.java:65)
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at org.json.simple.parser.JSONParser.parse(Unknown Source)
	at org.geotools.geojson.GeoJSONUtil.parse(GeoJSONUtil.java:236)
	at org.geotools.geojson.geom.GeometryJSON.parse(GeometryJSON.java:651)
	at org.geotools.geojson.geom.GeometryJSON.read(GeometryJSON.java:192)
	at org.geotools.geojson.geom.GeometryJSON$read.call(Unknown Source)
	at au.org.ala.ecodata.Site$__clinit__closure4_closure6.doCall(Site.groovy:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at groovy.lang.Closure.call(Closure.java:423)
	at org.codehaus.groovy.grails.validation.ValidatorConstraint.processValidate(ValidatorConstraint.java:85)
	at org.codehaus.groovy.grails.validation.AbstractConstraint.validate(AbstractConstraint.java:107)
	at org.codehaus.groovy.grails.validation.ConstrainedProperty.validate(ConstrainedProperty.java:983)
	at org.codehaus.groovy.grails.validation.GrailsDomainClassValidator.validatePropertyWithConstraint(GrailsDomainClassValidator.java:209)
	at org.codehaus.groovy.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:79)
	at org.codehaus.groovy.grails.validation.CascadingValidator$validate.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.grails.validation.CascadingValidator$validate.call(Unknown Source)
	at org.grails.datastore.gorm.GormValidationApi.doValidate(GormValidationApi.groovy:64)
	at org.grails.datastore.gorm.GormValidationApi.this$4$doValidate(GormValidationApi.groovy)
	at sun.reflect.GeneratedMethodAccessor1802.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at org.grails.datastore.gorm.GormValidationApi.validate(GormValidationApi.groovy:145)
	at au.org.ala.ecodata.Site.validate(Site.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:172)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy)
	at org.grails.datastore.gorm.GormInstanceApi$_save_closure5.doCall(GormInstanceApi.groovy:162)
	at sun.reflect.GeneratedMethodAccessor1800.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at groovy.lang.Closure.call(Closure.java:423)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:51)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:103)
	at com.sun.proxy.$Proxy92.doInSession(Unknown Source)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:302)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:161)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:101)
	at au.org.ala.ecodata.Site.save(Site.groovy)
	at au.org.ala.ecodata.Site$save.call(Unknown Source)
	at au.org.ala.ecodata.SiteService$_deleteSitesFromProject_closure11.doCall(SiteService.groovy:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1379)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1372)
	at org.codehaus.groovy.runtime.dgm$149.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at au.org.ala.ecodata.SiteService.deleteSitesFromProject(SiteService.groovy:228)
	at au.org.ala.ecodata.SiteService.deleteSitesFromProject(SiteService.groovy)
	at au.org.ala.ecodata.SiteService$deleteSitesFromProject$8.call(Unknown Source)
	at au.org.ala.ecodata.ProjectService.delete(ProjectService.groovy:387)
	at au.org.ala.ecodata.ProjectService$delete$15.call(Unknown Source)
	at au.org.ala.ecodata.ProjectController.delete(ProjectController.groovy:109)
	at au.org.ala.ecodata.ProjectController.delete(ProjectController.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.grails.web.servlet.mvc.MixedGrailsControllerHelper.invoke(MixedGrailsControllerHelper.java:154)
	at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleAction(AbstractGrailsControllerHelper.java:375)
	at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.executeAction(AbstractGrailsControllerHelper.java:252)
	at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleURI(AbstractGrailsControllerHelper.java:205)
	at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleURI(AbstractGrailsControllerHelper.java:126)
	at org.codehaus.groovy.grails.web.servlet.mvc.SimpleGrailsController.handleRequest(SimpleGrailsController.java:72)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.codehaus.groovy.grails.web.servlet.GrailsDispatcherServlet.doDispatch(GrailsDispatcherServlet.java:347)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
	at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:885)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
	at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequestForUrlMappingInfo(UrlMappingUtils.java:178)
	at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequestForUrlMappingInfo(UrlMappingUtils.java:144)
	at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequestForUrlMappingInfo(UrlMappingUtils.java:135)
	at org.codehaus.groovy.grails.web.mapping.filter.UrlMappingsFilter.doFilterInternal(UrlMappingsFilter.java:216)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.codehaus.groovy.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:69)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.codehaus.groovy.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-11-24 11:42:27,823 [http-bio-8080-exec-3] ERROR StackTrace  - Full Stack Trace:
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at org.geotools.geojson.GeoJSONUtil.createCoordinate(GeoJSONUtil.java:212)
	at org.geotools.geojson.geom.GeometryHandlerBase.coordinate(GeometryHandlerBase.java:54)
	at org.geotools.geojson.geom.PolygonHandler.endArray(PolygonHandler.java:88)
	at org.geotools.geojson.RecordingHandler$6.run(RecordingHandler.java:90)
	at org.geotools.geojson.RecordingHandler.replay(RecordingHandler.java:127)
	at org.geotools.geojson.geom.GeometryHandler.primitive(GeometryHandler.java:65)
	at org.geotools.geojson.GeoJSONUtil.parse(GeoJSONUtil.java:236)
	at org.geotools.geojson.geom.GeometryJSON.parse(GeometryJSON.java:651)
	at org.geotools.geojson.geom.GeometryJSON.read(GeometryJSON.java:192)
	at au.org.ala.ecodata.Site$__clinit__closure4_closure6.doCall(Site.groovy:61)
	at org.grails.datastore.gorm.GormValidationApi.doValidate(GormValidationApi.groovy:64)
	at org.grails.datastore.gorm.GormValidationApi.validate(GormValidationApi.groovy:145)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:172)
	at org.grails.datastore.gorm.GormInstanceApi$_save_closure5.doCall(GormInstanceApi.groovy:162)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:302)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:161)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:101)
	at au.org.ala.ecodata.SiteService$_deleteSitesFromProject_closure11.doCall(SiteService.groovy:231)
	at au.org.ala.ecodata.SiteService.deleteSitesFromProject(SiteService.groovy:228)
	at au.org.ala.ecodata.ProjectService.delete(ProjectService.groovy:387)
	at au.org.ala.ecodata.ProjectController.delete(ProjectController.groovy:109)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-11-24 11:42:27,826 [http-bio-8080-exec-3] ERROR StackTrace  - Full Stack Trace:
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at org.geotools.geojson.GeoJSONUtil.createCoordinate(GeoJSONUtil.java:212)
	at org.geotools.geojson.geom.GeometryHandlerBase.coordinate(GeometryHandlerBase.java:54)
	at org.geotools.geojson.geom.PolygonHandler.endArray(PolygonHandler.java:88)
	at org.geotools.geojson.RecordingHandler$6.run(RecordingHandler.java:90)
	at org.geotools.geojson.RecordingHandler.replay(RecordingHandler.java:127)
	at org.geotools.geojson.geom.GeometryHandler.primitive(GeometryHandler.java:65)
	at org.geotools.geojson.GeoJSONUtil.parse(GeoJSONUtil.java:236)
	at org.geotools.geojson.geom.GeometryJSON.parse(GeometryJSON.java:651)
	at org.geotools.geojson.geom.GeometryJSON.read(GeometryJSON.java:192)
	at au.org.ala.ecodata.Site$__clinit__closure4_closure6.doCall(Site.groovy:61)
	at org.grails.datastore.gorm.GormValidationApi.doValidate(GormValidationApi.groovy:64)
	at org.grails.datastore.gorm.GormValidationApi.validate(GormValidationApi.groovy:145)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:172)
	at org.grails.datastore.gorm.GormInstanceApi$_save_closure5.doCall(GormInstanceApi.groovy:162)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:302)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:161)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:101)
	at au.org.ala.ecodata.SiteService$_deleteSitesFromProject_closure11.doCall(SiteService.groovy:231)
	at au.org.ala.ecodata.SiteService.deleteSitesFromProject(SiteService.groovy:228)
	at au.org.ala.ecodata.ProjectService.delete(ProjectService.groovy:387)
	at au.org.ala.ecodata.ProjectController.delete(ProjectController.groovy:109)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-11-24 11:42:27,826 [http-bio-8080-exec-3] ERROR StackTrace  - Full Stack Trace:
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at org.geotools.geojson.GeoJSONUtil.createCoordinate(GeoJSONUtil.java:212)
	at org.geotools.geojson.geom.GeometryHandlerBase.coordinate(GeometryHandlerBase.java:54)
	at org.geotools.geojson.geom.PolygonHandler.endArray(PolygonHandler.java:88)
	at org.geotools.geojson.RecordingHandler$6.run(RecordingHandler.java:90)
	at org.geotools.geojson.RecordingHandler.replay(RecordingHandler.java:127)
	at org.geotools.geojson.geom.GeometryHandler.primitive(GeometryHandler.java:65)
	at org.geotools.geojson.GeoJSONUtil.parse(GeoJSONUtil.java:236)
	at org.geotools.geojson.geom.GeometryJSON.parse(GeometryJSON.java:651)
	at org.geotools.geojson.geom.GeometryJSON.read(GeometryJSON.java:192)
	at au.org.ala.ecodata.Site$__clinit__closure4_closure6.doCall(Site.groovy:61)
	at org.grails.datastore.gorm.GormValidationApi.doValidate(GormValidationApi.groovy:64)
	at org.grails.datastore.gorm.GormValidationApi.validate(GormValidationApi.groovy:145)
	at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:172)
	at org.grails.datastore.gorm.GormInstanceApi$_save_closure5.doCall(GormInstanceApi.groovy:162)
	at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:302)
	at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:161)
	at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:101)
	at au.org.ala.ecodata.SiteService$_deleteSitesFromProject_closure11.doCall(SiteService.groovy:231)
	at au.org.ala.ecodata.SiteService.deleteSitesFromProject(SiteService.groovy:228)
	at au.org.ala.ecodata.ProjectService.delete(ProjectService.groovy:387)
	at au.org.ala.ecodata.ProjectController.delete(ProjectController.groovy:109)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

`

**Comment by temi** [comment]
https://upsource.ala.org.au/ala-map-plugin/review/AMP-CR-17
